name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -m unittest discover tests -v

  deploy:
    name: Деплой на production
    runs-on: self-hosted
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    - run: |
        mkdir -p ~/mortgage-calculator
        cp app.py calculator.py ~/mortgage-calculator/
        echo "Приложение развернуто в ~/mortgage-calculator"
    - run: |
        cd ~/mortgage-calculator
        echo -e "1000000\n7.5\n20" | python3 app.py