name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Run unit tests
      run: |
        echo "Запуск тестов калькулятора"
        python -m unittest tests/test_calculator.py -v
    
    - name: Run integration tests
      run: |
        echo "Запуск тестов приложения"
        python -m unittest tests/test_app.py -v
    
    - name: Test the application
      run: |
        echo "Тестируем работу приложения"
        echo "1000000" > test_input.txt
        echo "7.5" >> test_input.txt
        echo "20" >> test_input.txt
        python app.py < test_input.txt || echo "Приложение завершило работу"

  deploy:
    name: Деплой на production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
    
    - name: Deploy to production
      run: |
        echo "Деплой на сервер: ${{ secrets.SERVER_HOST }}"
        
        # Копируем файлы
        scp -o StrictHostKeyChecking=no \
            app.py calculator.py \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/mortgage-calculator/
        
        # Проверяем деплой
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          echo 'Файлы скопированы на сервер'
          echo 'Содержимое папки:'
          ls -la /opt/mortgage-calculator/
          echo 'Тестируем приложение:'
          cd /opt/mortgage-calculator
          echo -e '1000000\\n7.5\\n20' | python3 app.py
        "
        
    - name: Deployment summary
      run: |
        echo "ДЕПЛОЙ ЗАВЕРШЕН"
        echo "Приложение установлено на: ${{ secrets.SERVER_HOST }}"
        echo "Для запуска: cd /opt/mortgage-calculator && python3 app.py"