name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -m unittest discover tests -v

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy application
      run: |
        mkdir -p ~/mortgage-calculator
        cp app.py calculator.py ~/mortgage-calculator/
    
    - name: Test deployed application
      run: |
        cd ~/mortgage-calculator
        echo -e "1000000\n7.5\n20" | python3 app.py
    
    - name: Final deployment test
      run: |
        cd ~/mortgage-calculator
        echo -e "2000000\n8.5\n15" | python3 app.py